/**
 * Light of Day — Complete 78-card Tarot Deck Data
 * All card designs are original (CSS-rendered). No copyrighted artwork.
 * Meanings based on traditional Rider-Waite-Smith interpretations (public domain knowledge).
 */

const TAROT_DECK = [
  // ═══════════════════════════════════════
  //  MAJOR ARCANA (0 – XXI)
  // ═══════════════════════════════════════
  {
    id: 0, name: "The Fool", numeral: "0", arcana: "major", suit: null,
    symbol: "🌟", element: "Air", zodiac: "Uranus",
    keywords: ["new beginnings", "innocence", "spontaneity", "free spirit"],
    upright: "A fresh start beckons. The Fool steps forward with pure trust in the universe, unencumbered by fear or doubt. Embrace the unknown — a leap of faith leads to adventure and self-discovery. Let go of what no longer serves you and welcome infinite possibility.",
    reversed: "Recklessness and naivety cloud your judgement. You may be taking unnecessary risks or ignoring obvious warning signs. Pause before that leap — not every cliff has a soft landing. Consider whether your spontaneity is masking a fear of commitment.",
  },
  {
    id: 1, name: "The Magician", numeral: "I", arcana: "major", suit: null,
    symbol: "✨", element: "Air", zodiac: "Mercury",
    keywords: ["willpower", "creation", "manifestation", "resourcefulness"],
    upright: "You hold all the tools you need. The Magician channels cosmic energy into earthly action — this is a time of immense creative power. Focus your intention, align your resources, and manifest your vision into reality. The universe says yes.",
    reversed: "Manipulation, trickery, or untapped potential. You may be deceiving yourself or others, or perhaps your talents lie dormant. Beware of illusions and quick-fix schemes. Reconnect with your authentic power rather than relying on smoke and mirrors.",
  },
  {
    id: 2, name: "The High Priestess", numeral: "II", arcana: "major", suit: null,
    symbol: "🌙", element: "Water", zodiac: "Moon",
    keywords: ["intuition", "mystery", "inner knowledge", "the subconscious"],
    upright: "Look inward. The High Priestess guards the threshold between the seen and unseen worlds. Trust your intuition — the answers you seek are already within you. This is a time for quiet reflection, meditation, and listening to the whispers of your subconscious.",
    reversed: "You are ignoring your inner voice or projecting your shadow onto others. Secrets may be kept from you, or you may be in denial. The noise of the external world is drowning out your intuition. Find stillness; the truth will surface.",
  },
  {
    id: 3, name: "The Empress", numeral: "III", arcana: "major", suit: null,
    symbol: "👑", element: "Earth", zodiac: "Venus",
    keywords: ["abundance", "nurturing", "fertility", "nature"],
    upright: "Abundance flows. The Empress invites you to embrace pleasure, creativity, and the beauty of the natural world. This is a time of growth, nurturing relationships, and enjoying the fruits of your labor. Create, love, and let life blossom around you.",
    reversed: "Creative blocks, neglect of self-care, or smothering others with too much attention. You may be disconnected from nature or your own body. An imbalance between giving and receiving needs attention. Nourish yourself before you can nourish others.",
  },
  {
    id: 4, name: "The Emperor", numeral: "IV", arcana: "major", suit: null,
    symbol: "⚔️", element: "Fire", zodiac: "Aries",
    keywords: ["authority", "structure", "stability", "leadership"],
    upright: "Take command. The Emperor brings order from chaos through discipline and strategic thinking. Now is the time to establish firm foundations, set boundaries, and lead with confidence. Structure and stability will carry you forward.",
    reversed: "Tyranny, rigidity, or lack of discipline. Authority is being abused or entirely absent. You may be either too controlling or too passive. Find the balance between firm leadership and flexible compassion.",
  },
  {
    id: 5, name: "The Hierophant", numeral: "V", arcana: "major", suit: null,
    symbol: "📿", element: "Earth", zodiac: "Taurus",
    keywords: ["tradition", "wisdom", "spiritual guidance", "conformity"],
    upright: "Seek wisdom from established traditions and trusted mentors. The Hierophant represents spiritual teachings, institutions, and the shared knowledge of those who came before. A teacher or guide may appear, or you may become one yourself.",
    reversed: "Challenging conventions, breaking free from dogma, or feeling restricted by traditions. This can also signal a personal spiritual awakening that takes you beyond established systems. Question what you've been taught — forge your own path.",
  },
  {
    id: 6, name: "The Lovers", numeral: "VI", arcana: "major", suit: null,
    symbol: "❤️", element: "Air", zodiac: "Gemini",
    keywords: ["love", "harmony", "choices", "union"],
    upright: "A profound connection or pivotal choice stands before you. The Lovers represent not just romance but the harmony of opposites — head and heart, self and other. Choose with both love and wisdom. Authentic relationships deepen now.",
    reversed: "Disharmony, misalignment of values, or avoidance of a difficult choice. A relationship may be out of balance, or you're torn between options. Face the decision honestly — avoiding it only prolongs the tension.",
  },
  {
    id: 7, name: "The Chariot", numeral: "VII", arcana: "major", suit: null,
    symbol: "🏆", element: "Water", zodiac: "Cancer",
    keywords: ["determination", "triumph", "willpower", "direction"],
    upright: "Victory through sheer willpower. The Chariot surges forward — harness opposing forces and steer them toward your goal. Confidence, determination, and focused action will carry you through any obstacle. Stay the course; triumph is near.",
    reversed: "Loss of direction, scattered energy, or aggression without purpose. You may be forcing outcomes or losing control of a situation. Step back, recalibrate your compass, and ensure your ambition hasn't become obsession.",
  },
  {
    id: 8, name: "Strength", numeral: "VIII", arcana: "major", suit: null,
    symbol: "🦁", element: "Fire", zodiac: "Leo",
    keywords: ["courage", "patience", "inner strength", "compassion"],
    upright: "True strength is gentle. This card speaks of quiet courage, patience, and the power of compassion over brute force. Tame your inner lions with love, not chains. Your resilience and grace under pressure will see you through.",
    reversed: "Self-doubt, weakness, or raw uncontrolled emotions. You may be giving in to fear or lashing out from insecurity. Remember that vulnerability is not weakness — but avoiding your feelings is. Reconnect with your inner resolve.",
  },
  {
    id: 9, name: "The Hermit", numeral: "IX", arcana: "major", suit: null,
    symbol: "🔮", element: "Earth", zodiac: "Virgo",
    keywords: ["solitude", "soul-searching", "inner guidance", "contemplation"],
    upright: "Withdraw from the noise. The Hermit's lantern illuminates the path inward — this is a time for deep reflection, meditation, and soul-searching. Wisdom comes from solitude. The answers you seek are found in quiet contemplation, not in the clamor of others.",
    reversed: "Isolation, loneliness, or withdrawal taken too far. You may be refusing helpful counsel or hiding from the world out of fear. Solitude nurtures wisdom, but prolonged isolation breeds stagnation. Reach out when you're ready.",
  },
  {
    id: 10, name: "Wheel of Fortune", numeral: "X", arcana: "major", suit: null,
    symbol: "☸️", element: "Fire", zodiac: "Jupiter",
    keywords: ["cycles", "destiny", "turning point", "luck"],
    upright: "The wheel turns. Fate delivers a pivotal shift — cycles end and begin, luck changes hands, and destiny calls. Embrace change as the natural rhythm of life. What goes up must come down, and what falls will rise again. Trust the process.",
    reversed: "Resistance to change, bad luck, or feeling stuck in an unwanted cycle. External forces seem to work against you. Remember: this too shall pass. The wheel never stops turning — your fortunes will shift again.",
  },
  {
    id: 11, name: "Justice", numeral: "XI", arcana: "major", suit: null,
    symbol: "⚖️", element: "Air", zodiac: "Libra",
    keywords: ["fairness", "truth", "accountability", "balance"],
    upright: "Truth and fairness prevail. Justice asks you to weigh all sides impartially and take responsibility for your actions. Legal matters may resolve in your favor if you've acted with integrity. Cause and effect are at work — what you sow, you shall reap.",
    reversed: "Injustice, dishonesty, or avoidance of accountability. The scales are tipped — bias, unfairness, or denial of consequences clouds the situation. Examine where you may be rationalizing unethical behavior, in yourself or others.",
  },
  {
    id: 12, name: "The Hanged Man", numeral: "XII", arcana: "major", suit: null,
    symbol: "🔄", element: "Water", zodiac: "Neptune",
    keywords: ["surrender", "new perspective", "pause", "letting go"],
    upright: "Surrender to gain clarity. The Hanged Man suspends action to shift perspective — sometimes you must let go of control to see the truth. This pause is not punishment but illumination. What once seemed impossible becomes clear when viewed from a new angle.",
    reversed: "Stalling, martyrdom, or refusing to see another viewpoint. You may cling to a situation that demands release, or sacrifice yourself unnecessarily. The delay you resist may be the very thing that frees you.",
  },
  {
    id: 13, name: "Death", numeral: "XIII", arcana: "major", suit: null,
    symbol: "🦋", element: "Water", zodiac: "Scorpio",
    keywords: ["transformation", "endings", "rebirth", "release"],
    upright: "An ending that births something new. Death is transformation — not destruction. A chapter closes so another can begin. Release what has run its course with grace. From the ashes of the old, the new self rises, stronger and more authentic than before.",
    reversed: "Resisting inevitable change, stagnation, or clinging to the past. Fear of endings keeps you trapped in situations that no longer serve your growth. Let go — the longer you resist, the more painful the transition becomes.",
  },
  {
    id: 14, name: "Temperance", numeral: "XIV", arcana: "major", suit: null,
    symbol: "⏳", element: "Fire", zodiac: "Sagittarius",
    keywords: ["balance", "moderation", "patience", "harmony"],
    upright: "Find the middle way. Temperance blends opposing forces into perfect harmony — patience, moderation, and divine timing are your allies. Healing flows when you balance work and rest, giving and receiving, spirit and matter. Trust the alchemical process.",
    reversed: "Excess, imbalance, or impatience disrupts your harmony. You may be overindulging, rushing, or losing your center. Step back from extremes and find equilibrium before moving forward.",
  },
  {
    id: 15, name: "The Devil", numeral: "XV", arcana: "major", suit: null,
    symbol: "⛓️", element: "Earth", zodiac: "Capricorn",
    keywords: ["shadow self", "attachment", "addiction", "materialism"],
    upright: "Confront your chains. The Devil reveals bondage to material desires, addictions, or toxic patterns — but the chains are looser than they appear. Awareness is the first step to liberation. Shine light on your shadow to reclaim your power.",
    reversed: "Breaking free from addiction, releasing attachments, or a moment of clarity about self-destructive patterns. Liberation is at hand — but it requires courage to walk away. You are stronger than your chains.",
  },
  {
    id: 16, name: "The Tower", numeral: "XVI", arcana: "major", suit: null,
    symbol: "⚡", element: "Fire", zodiac: "Mars",
    keywords: ["upheaval", "revelation", "sudden change", "awakening"],
    upright: "The lightning strikes. The Tower shatters illusions and false structures — sudden upheaval clears the way for rebuilding on authentic foundations. It may feel devastating, but destruction of the false self reveals the true one. From rubble comes rebirth.",
    reversed: "Resisting inevitable breakdown, fear of change, or a less dramatic upheaval. You may be clinging to a crumbling structure or the worst has already passed. Sometimes the tower falls slowly rather than all at once.",
  },
  {
    id: 17, name: "The Star", numeral: "XVII", arcana: "major", suit: null,
    symbol: "⭐", element: "Air", zodiac: "Aquarius",
    keywords: ["hope", "renewal", "inspiration", "serenity"],
    upright: "After the storm, the stars appear. Hope, healing, and inspiration pour down like starlight. The Star brings renewal of faith and a sense of cosmic connection. You are exactly where you need to be. Trust, breathe, and let the universe hold you.",
    reversed: "Loss of hope, disconnection, or feeling uninspired. The light at the end of the tunnel seems dim. Remember that stars are always present — even when clouds hide them. Reconnect with what gives your life meaning.",
  },
  {
    id: 18, name: "The Moon", numeral: "XVIII", arcana: "major", suit: null,
    symbol: "🌕", element: "Water", zodiac: "Pisces",
    keywords: ["illusion", "intuition", "the unconscious", "fear"],
    upright: "Navigate the shadows. The Moon illuminates the realm of dreams, illusions, and deep intuition. Things are not as they seem — trust your instincts even when logic falters. Face your fears rather than let them control you from the depths.",
    reversed: "Clarity emerging from confusion, releasing fears, or deception revealed. The fog begins to lift. Repressed emotions surface for healing. What was hidden in moonlight becomes visible in the approaching dawn.",
  },
  {
    id: 19, name: "The Sun", numeral: "XIX", arcana: "major", suit: null,
    symbol: "☀️", element: "Fire", zodiac: "Sun",
    keywords: ["joy", "success", "vitality", "clarity"],
    upright: "Radiant joy and success. The Sun shines its warmth upon you — clarity replaces confusion, vitality returns, and everything touched by this light flourishes. Celebrate your achievements, embrace your inner child, and bask in the glow of well-earned happiness.",
    reversed: "Temporary setbacks in happiness, overly optimistic expectations, or dimmed vitality. The sun still shines but clouds partially obscure it. Don't lose faith — the warmth will return in full. Tend to your inner light.",
  },
  {
    id: 20, name: "Judgement", numeral: "XX", arcana: "major", suit: null,
    symbol: "📯", element: "Fire", zodiac: "Pluto",
    keywords: ["reckoning", "absolution", "calling", "rebirth"],
    upright: "The trumpet sounds — answer the call. Judgement brings a moment of profound reckoning and spiritual awakening. Review your past with honesty, forgive yourself and others, and rise renewed. A higher purpose beckons. This is your moment of resurrection.",
    reversed: "Self-doubt, refusal to learn from the past, or ignoring your calling. You may be too harsh in self-judgement or avoiding accountability. The call to transformation goes unanswered — but it will sound again. Listen.",
  },
  {
    id: 21, name: "The World", numeral: "XXI", arcana: "major", suit: null,
    symbol: "🌍", element: "Earth", zodiac: "Saturn",
    keywords: ["completion", "integration", "accomplishment", "wholeness"],
    upright: "The cycle is complete. The World celebrates mastery, integration, and the fulfillment of a great journey. You have arrived — honour what you've achieved and the wisdom you've gathered. A moment of wholeness and unity with all things. Now, a new cycle begins.",
    reversed: "Incompletion, shortcuts, or delays in reaching your goals. The finish line is in sight but something holds you back. Tie up loose ends, complete unfinished business, and trust that closure will come.",
  },

  // ═══════════════════════════════════════
  //  MINOR ARCANA — WANDS (Fire)
  // ═══════════════════════════════════════
  {
    id: 22, name: "Ace of Wands", numeral: "A", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["inspiration", "new venture", "creative spark"],
    upright: "A bolt of inspiration ignites. New creative ventures, passionate beginnings, and the spark of potential await. Seize this energy and channel it into action.",
    reversed: "Delays in new projects, lack of motivation, or misdirected passion. The spark is there but it needs tending. Don't let creative energy fizzle out.",
  },
  {
    id: 23, name: "Two of Wands", numeral: "2", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["planning", "decisions", "future vision"],
    upright: "You stand at the threshold of possibility. Planning, vision, and bold decisions shape your future. The world is in your hands — choose your direction with confidence.",
    reversed: "Fear of the unknown, poor planning, or lack of ambition. You may be stuck in your comfort zone or overwhelmed by choices. Take the first step.",
  },
  {
    id: 24, name: "Three of Wands", numeral: "3", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["expansion", "foresight", "progress"],
    upright: "Your ships are coming in. Plans set in motion are bearing fruit, and the horizon expands with opportunity. Stay the course — expansion and growth are underway.",
    reversed: "Delays in plans, frustration with progress, or playing it too safe. Don't lose faith. Obstacles are temporary — recalibrate and press forward.",
  },
  {
    id: 25, name: "Four of Wands", numeral: "4", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["celebration", "harmony", "homecoming"],
    upright: "A time of celebration, stability, and joyful milestones. Community, family, and a sense of belonging flourish. Enjoy this moment of harmony and togetherness.",
    reversed: "Lack of harmony at home, cancelled celebrations, or feeling unwelcome. Inner tensions disrupt what should be peaceful. Address the root cause before decorating the surface.",
  },
  {
    id: 26, name: "Five of Wands", numeral: "5", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["conflict", "competition", "tension"],
    upright: "Clashing energies and competitive tensions surround you. Conflict can be constructive if channeled properly — diverse viewpoints sharpen ideas. Rise above petty squabbles and focus on growth.",
    reversed: "Avoiding conflict, finding common ground, or internalized frustration. The struggle may be ending, or you're suppressing valid disagreements. Healthy confrontation leads to resolution.",
  },
  {
    id: 27, name: "Six of Wands", numeral: "6", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["victory", "recognition", "triumph"],
    upright: "Public recognition and well-earned victory. Your efforts are celebrated and your leadership is acknowledged. Ride this wave of success with humility and grace.",
    reversed: "Ego, fall from grace, or lack of recognition. Success may be hollow or short-lived. Seek validation from within rather than from the crowd.",
  },
  {
    id: 28, name: "Seven of Wands", numeral: "7", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["courage", "perseverance", "defense"],
    upright: "Stand your ground. Challenges and opposition test your resolve, but you hold the high ground. Defend your position with courage — your persistence will outlast the pressure.",
    reversed: "Overwhelmed by opposition, giving up too easily, or feeling defensive. Know when to hold firm and when to strategically retreat. Exhaustion weakens your stance.",
  },
  {
    id: 29, name: "Eight of Wands", numeral: "8", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["speed", "momentum", "swift action"],
    upright: "Everything accelerates. Messages, travel, and swift developments surge forward. Strike while the iron is hot — momentum is on your side. Events unfold rapidly; be ready to act.",
    reversed: "Delays, frustration, or scattered energy. Things slow down unexpectedly. Patience is required — forcing speed now may cause mistakes. Regroup and wait for the right moment.",
  },
  {
    id: 30, name: "Nine of Wands", numeral: "9", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["resilience", "persistence", "last stand"],
    upright: "Battered but unbroken. You've faced many trials and one final challenge remains. Draw on your deep reserves of strength — you're closer to victory than you think. Don't give up now.",
    reversed: "Exhaustion, stubbornness, or paranoia. You may be fighting battles that no longer need fighting. Rest is not defeat. Know when to lower your guard and accept help.",
  },
  {
    id: 31, name: "Ten of Wands", numeral: "10", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["burden", "responsibility", "hard work"],
    upright: "Heavy is the load. You carry great responsibility — perhaps too much. Success has brought burdens. Delegate, prioritize, and remember that carrying everything yourself is not strength; it's stubbornness.",
    reversed: "Releasing burdens, delegating, or burnout. The weight is becoming unbearable. It's time to put some wands down. Simplify your commitments before you collapse under them.",
  },
  {
    id: 32, name: "Page of Wands", numeral: "P", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["enthusiasm", "exploration", "discovery"],
    upright: "A messenger of passion and adventure. New ideas excite you, creative projects beckon, and the spirit of exploration is strong. Embrace your curiosity and dare to try something new.",
    reversed: "Lack of direction, immaturity, or hasty decisions. Enthusiasm without follow-through leads nowhere. Ground your excitement in a plan before charging ahead.",
  },
  {
    id: 33, name: "Knight of Wands", numeral: "Kn", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["action", "adventure", "impulsiveness"],
    upright: "Charge forward with fiery determination. The Knight of Wands brings energy, boldness, and a thirst for adventure. Take decisive action and pursue your passions with fearless abandon.",
    reversed: "Recklessness, impatience, or scattered energy. Passion without direction leads to burnout. Haste makes waste — slow down enough to aim before you fire.",
  },
  {
    id: 34, name: "Queen of Wands", numeral: "Q", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["confidence", "warmth", "determination"],
    upright: "Radiate confidence and warmth. The Queen of Wands embodies magnetic charisma, creative mastery, and fierce determination. Lead with passion, inspire others, and trust in your vision.",
    reversed: "Jealousy, insecurity, or domineering behavior. Your fire may be burning others or yourself. Check whether confidence has tipped into arrogance, or if self-doubt dims your natural glow.",
  },
  {
    id: 35, name: "King of Wands", numeral: "K", arcana: "minor", suit: "wands",
    symbol: "🔥", element: "Fire",
    keywords: ["leadership", "vision", "entrepreneurship"],
    upright: "A visionary leader who turns dreams into empires. The King of Wands commands with charisma and bold strategy. Take charge of your destiny, inspire your team, and lead by example.",
    reversed: "Tyrannical leadership, unrealistic expectations, or burnout at the top. Power without wisdom creates chaos. Listen to counsel and remember that true leaders serve their people.",
  },

  // ═══════════════════════════════════════
  //  MINOR ARCANA — CUPS (Water)
  // ═══════════════════════════════════════
  {
    id: 36, name: "Ace of Cups", numeral: "A", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["new love", "emotional awakening", "compassion"],
    upright: "The cup overflows with love. A new emotional beginning — deep connections, compassion, and creative inspiration pour into your life. Open your heart and receive.",
    reversed: "Emotional blockage, repressed feelings, or emptiness. The cup is turned away. Heal old wounds before you can receive new love. Self-love is the first cup to fill.",
  },
  {
    id: 37, name: "Two of Cups", numeral: "2", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["partnership", "mutual attraction", "unity"],
    upright: "Two souls meet in harmony. Deep connection, mutual respect, and balanced partnership flourish. Whether romantic or platonic, this bond is genuine and nourishing.",
    reversed: "Imbalance in a relationship, breakup, or miscommunication. One cup may be fuller than the other. Address the disparity before resentment takes root.",
  },
  {
    id: 38, name: "Three of Cups", numeral: "3", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["celebration", "friendship", "community"],
    upright: "Raise your cups in celebration! Friendship, community, and shared joy bring warmth to your life. Gather with those you love and celebrate the bonds that sustain you.",
    reversed: "Gossip, overindulgence, or social isolation. The party may have gone too far, or you feel left out. Balance social life with personal boundaries.",
  },
  {
    id: 39, name: "Four of Cups", numeral: "4", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["contemplation", "apathy", "re-evaluation"],
    upright: "A moment of discontent and contemplation. You may overlook blessings while fixating on what's missing. Look up — an opportunity is being offered that you might not see. Re-evaluate your emotional landscape.",
    reversed: "Renewed motivation, seizing opportunities, or emerging from a funk. The apathy lifts and you see clearly again. Accept what the universe offers.",
  },
  {
    id: 40, name: "Five of Cups", numeral: "5", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["grief", "loss", "regret"],
    upright: "Three cups have spilled, but two remain standing. Grief and regret demand attention, but don't let sorrow blind you to what remains. Mourn what's lost, then turn around — hope still stands behind you.",
    reversed: "Acceptance, moving on, or finding silver linings. The grieving period ends and healing begins. You choose to focus on what remains rather than what was lost.",
  },
  {
    id: 41, name: "Six of Cups", numeral: "6", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["nostalgia", "innocence", "reunion"],
    upright: "Sweet memories and innocent joy return. The Six of Cups brings nostalgia, childhood connections, and simple pleasures. A reunion or gift from the past may arrive. Embrace the warmth of happy memories.",
    reversed: "Living in the past, naivety, or an inability to move forward. Nostalgia becomes a trap when it prevents growth. Honor your memories but live in the present.",
  },
  {
    id: 42, name: "Seven of Cups", numeral: "7", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["fantasy", "choices", "illusion"],
    upright: "Many cups float in the clouds — dreams, fantasies, and wishful thinking abound. Not every glittering option is real. Distinguish between genuine opportunities and illusions before committing.",
    reversed: "Clarity of purpose, narrowing choices, or disillusionment. The fog of fantasy clears and reality sharpens. Make grounded decisions based on what is, not what you wish could be.",
  },
  {
    id: 43, name: "Eight of Cups", numeral: "8", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["departure", "searching", "letting go"],
    upright: "Walking away from what no longer fulfills you. The Eight of Cups is a brave departure — leaving behind the familiar in search of deeper meaning. The journey is lonely but necessary. Trust that something better awaits.",
    reversed: "Fear of leaving, drifting aimlessly, or returning to an old situation. You know you should move on but can't find the courage. Sometimes the hardest step is the first one away.",
  },
  {
    id: 44, name: "Nine of Cups", numeral: "9", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["contentment", "wish fulfilled", "satisfaction"],
    upright: "The wish card. Emotional satisfaction, dreams fulfilled, and a deep sense of contentment wash over you. Enjoy this moment — you've earned it. Gratitude amplifies the joy.",
    reversed: "Dissatisfaction despite having much, greed, or shallow pleasures. Material comfort without emotional depth feels hollow. Look beyond the surface for true fulfillment.",
  },
  {
    id: 45, name: "Ten of Cups", numeral: "10", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["harmony", "family", "emotional fulfillment"],
    upright: "The rainbow of emotional fulfillment. Family harmony, lasting love, and deep happiness create a picture of wholeness. This is the happily-ever-after — cherish it and share your abundance with others.",
    reversed: "Family discord, broken dreams, or misaligned values. The ideal picture has cracks. Work on communication and shared goals to restore harmony in your closest relationships.",
  },
  {
    id: 46, name: "Page of Cups", numeral: "P", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["creativity", "intuition", "emotional message"],
    upright: "A gentle messenger brings emotional or creative news. The Page of Cups embodies youthful sensitivity, artistic inspiration, and intuitive insights. Stay open to unexpected emotional gifts.",
    reversed: "Emotional immaturity, creative blocks, or escapism. Sensitivity can become over-sensitivity. Ground your dreams in reality without losing their magic.",
  },
  {
    id: 47, name: "Knight of Cups", numeral: "Kn", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["romance", "charm", "idealism"],
    upright: "The romantic hero arrives. The Knight of Cups brings proposals, invitations, and emotionally charged opportunities. Follow your heart with grace and charm. Art, beauty, and love are your guides.",
    reversed: "Moodiness, unrealistic expectations, or emotional manipulation. The charming exterior may hide fickle intentions. Verify before you trust. Not every knight keeps their promises.",
  },
  {
    id: 48, name: "Queen of Cups", numeral: "Q", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["compassion", "emotional depth", "intuition"],
    upright: "Deep emotional wisdom and nurturing compassion define the Queen of Cups. She reads the currents of feeling with uncanny accuracy. Trust your emotional intelligence and care for others from a place of inner fullness.",
    reversed: "Emotional overwhelm, codependency, or martyrdom. You absorb others' pain at the cost of your own wellbeing. Set boundaries with love. You cannot pour from an empty cup.",
  },
  {
    id: 49, name: "King of Cups", numeral: "K", arcana: "minor", suit: "cups",
    symbol: "💧", element: "Water",
    keywords: ["emotional balance", "diplomacy", "wisdom"],
    upright: "Mastery of emotion. The King of Cups navigates turbulent waters with calm authority. He balances heart and mind, feeling deeply while acting wisely. Lead with emotional intelligence and compassionate authority.",
    reversed: "Emotional manipulation, volatility, or repression. The calm surface hides turbulent undercurrents. When a leader loses emotional control, everyone suffers. Seek help if the waters overwhelm you.",
  },

  // ═══════════════════════════════════════
  //  MINOR ARCANA — SWORDS (Air)
  // ═══════════════════════════════════════
  {
    id: 50, name: "Ace of Swords", numeral: "A", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["clarity", "breakthrough", "truth"],
    upright: "A blade of clarity cuts through confusion. A breakthrough in thinking, a flash of insight, or a decisive truth reveals itself. Wield this mental sharpness wisely — truth is powerful but also sharp.",
    reversed: "Confusion, misinformation, or a truth you're not ready to hear. The sword is dulled by deception or clouded thinking. Seek clarity before making decisions.",
  },
  {
    id: 51, name: "Two of Swords", numeral: "2", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["indecision", "stalemate", "difficult choice"],
    upright: "Blindfolded between two swords — a difficult decision demands resolution. Avoidance only prolongs the tension. Remove the blindfold, face the facts, and choose. Any choice is better than no choice.",
    reversed: "Information overload, lies revealed, or a decision finally made. The stalemate breaks, for better or worse. Trust your gut when logic alone cannot decide.",
  },
  {
    id: 52, name: "Three of Swords", numeral: "3", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["heartbreak", "sorrow", "painful truth"],
    upright: "Three swords pierce the heart. Grief, heartbreak, or a painful realization cuts deep. Allow yourself to feel the pain fully — suppressing sorrow only delays healing. This wound will eventually become wisdom.",
    reversed: "Recovery from heartbreak, releasing pain, or forgiveness. The swords begin to withdraw. Healing is underway, though scars may remain. Optimism slowly returns.",
  },
  {
    id: 53, name: "Four of Swords", numeral: "4", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["rest", "recovery", "contemplation"],
    upright: "Lay down your swords and rest. Mental exhaustion demands recovery — this is not retreat but necessary healing. Meditate, sleep, and let your mind recover. You'll return to battle stronger.",
    reversed: "Restlessness, burnout, or forced activity when rest is needed. You refuse to pause even as your mind screams for relief. Collapse is not a strategy. Rest now or break later.",
  },
  {
    id: 54, name: "Five of Swords", numeral: "5", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["conflict", "defeat", "hollow victory"],
    upright: "A battle won at great cost. The Five of Swords warns of pyrrhic victories and conflicts that leave everyone wounded. Consider whether winning this fight is worth what you'll lose. Choose your battles wisely.",
    reversed: "Reconciliation after conflict, learning from defeat, or walking away from a fight. Pride eventually yields to reason. An apology or olive branch may be necessary.",
  },
  {
    id: 55, name: "Six of Swords", numeral: "6", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["transition", "moving on", "calmer waters"],
    upright: "Leaving troubled waters behind. The Six of Swords marks a necessary transition — moving from turbulence toward calmer shores. The journey may be somber, but the destination brings peace. Better days lie ahead.",
    reversed: "Stuck in troubled waters, resistance to change, or unresolved baggage. You cannot sail to new shores while anchored to old harbors. Release what holds you back.",
  },
  {
    id: 56, name: "Seven of Swords", numeral: "7", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["deception", "strategy", "stealth"],
    upright: "Someone moves in shadows. The Seven of Swords signals deception, strategic thinking, or the need for a clever approach. Be mindful of who you trust. Sometimes unconventional tactics are necessary, but dishonesty has a price.",
    reversed: "Coming clean, getting caught, or releasing guilt. Secrets surface and deceptions unravel. Honesty, though difficult, is always the sharper sword.",
  },
  {
    id: 57, name: "Eight of Swords", numeral: "8", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["restriction", "helplessness", "self-imposed limitation"],
    upright: "Bound and blindfolded — but are the restraints real? The Eight of Swords reveals self-imposed prisons of fear and negative thinking. The cage has no lock; you can free yourself simply by choosing to. Change your thoughts, change your world.",
    reversed: "Self-liberation, new perspectives, or release from limiting beliefs. The blindfold slips and you realize you were never truly trapped. Freedom begins in the mind.",
  },
  {
    id: 58, name: "Nine of Swords", numeral: "9", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["anxiety", "nightmare", "despair"],
    upright: "The dark night of the soul. Anxiety, nightmares, and spiraling worry keep you awake. Your fears feel overwhelming, but many exist only in your mind. Reach out for support — you don't have to face the darkness alone.",
    reversed: "Light emerging from despair, recovery from anxiety, or the realization that fears were unfounded. Dawn approaches after the longest night. Seek help and hope.",
  },
  {
    id: 59, name: "Ten of Swords", numeral: "10", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["rock bottom", "endings", "betrayal"],
    upright: "Ten swords in the back — the absolute end. You've hit rock bottom, but there's strange comfort here: it cannot get worse. The darkest hour precedes the dawn. Release, grieve, and prepare to rise from the wreckage.",
    reversed: "Recovery, surviving the worst, or resisting an inevitable ending. You've survived what should have broken you. The swords will fall out one by one. Healing has begun.",
  },
  {
    id: 60, name: "Page of Swords", numeral: "P", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["curiosity", "vigilance", "new ideas"],
    upright: "A sharp young mind buzzes with questions and ideas. The Page of Swords is vigilant, curious, and ready to speak truth. Embrace intellectual curiosity and communicate your ideas with clarity and courage.",
    reversed: "Gossip, hasty words, or all talk with no action. A sharp tongue without wisdom cuts carelessly. Think before you speak and follow through on your ideas.",
  },
  {
    id: 61, name: "Knight of Swords", numeral: "Kn", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["ambition", "action", "driven"],
    upright: "The Knight charges with fierce intellectual determination. Swift action, ambitious pursuits, and single-minded focus drive you forward. Be bold in your convictions but mind that speed doesn't sacrifice accuracy.",
    reversed: "Ruthless ambition, tactless communication, or burnout from rushing. The sword swings wildly without aim. Slow down before you cut something — or someone — you didn't intend to.",
  },
  {
    id: 62, name: "Queen of Swords", numeral: "Q", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["independence", "clear thinking", "honest communication"],
    upright: "The Queen sees through all illusion with piercing clarity. Independent, articulate, and unafraid of hard truths, she cuts through nonsense with grace. Speak your truth clearly and set boundaries without apology.",
    reversed: "Cold-heartedness, bitterness, or weaponized intellect. Intelligence without empathy wounds. Past hurts have hardened your heart. Allow vulnerability back in alongside your sharp mind.",
  },
  {
    id: 63, name: "King of Swords", numeral: "K", arcana: "minor", suit: "swords",
    symbol: "💨", element: "Air",
    keywords: ["intellectual authority", "truth", "clear judgement"],
    upright: "The highest authority of mind and truth. The King of Swords governs with logic, fairness, and ethical clarity. Make decisions based on principles, not emotions. Your clear judgement guides others.",
    reversed: "Manipulation through intellect, abuse of authority, or cold disconnection. Power without compassion breeds tyranny. A brilliant mind without heart creates suffering.",
  },

  // ═══════════════════════════════════════
  //  MINOR ARCANA — PENTACLES (Earth)
  // ═══════════════════════════════════════
  {
    id: 64, name: "Ace of Pentacles", numeral: "A", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["new opportunity", "prosperity", "manifestation"],
    upright: "A golden seed of opportunity. Financial or material beginnings manifest — a new job, investment, or tangible reward appears. Plant it wisely and tend it well. Prosperity grows from here.",
    reversed: "Missed financial opportunity, poor planning, or scarcity mindset. The seed falls on rocky ground. Re-examine your relationship with money and material security.",
  },
  {
    id: 65, name: "Two of Pentacles", numeral: "2", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["balance", "adaptability", "juggling"],
    upright: "Juggling multiple priorities with skill and grace. The Two of Pentacles demands flexibility and balance — manage your resources, time, and energy wisely. Stay light on your feet.",
    reversed: "Overwhelm, financial imbalance, or dropping the ball. Too many plates spin at once. Simplify your commitments before something important crashes.",
  },
  {
    id: 66, name: "Three of Pentacles", numeral: "3", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["teamwork", "craftsmanship", "collaboration"],
    upright: "Skilled collaboration produces mastery. The Three of Pentacles celebrates teamwork, quality craftsmanship, and the early stages of building something lasting. Your skills are recognized and valued.",
    reversed: "Poor teamwork, lack of skill, or cutting corners. The foundation cracks without proper collaboration. Invest in quality and communication.",
  },
  {
    id: 67, name: "Four of Pentacles", numeral: "4", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["security", "control", "possessiveness"],
    upright: "Holding tightly to what you have. Financial security and control bring comfort, but beware of becoming possessive or miserly. True wealth flows; stagnant money breeds fear.",
    reversed: "Releasing control, generosity, or financial insecurity. You either let go of material attachment or lose what you clung to. Open hands receive more than clenched fists.",
  },
  {
    id: 68, name: "Five of Pentacles", numeral: "5", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["hardship", "poverty", "isolation"],
    upright: "Walking through winter's cold. Financial hardship, health struggles, or feeling left out in the cold test your resilience. Help may be closer than you think — look up and seek the warmth of community.",
    reversed: "Recovery from hardship, finding help, or ending a period of struggle. The worst has passed and warmth returns. Accept kindness offered to you.",
  },
  {
    id: 69, name: "Six of Pentacles", numeral: "6", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["generosity", "charity", "balance of giving"],
    upright: "The flow of generosity. Give and receive with open hands — charity, fairness, and shared prosperity create balance. Whether you're the giver or receiver, gratitude is the currency.",
    reversed: "Strings attached, debt, or conditional generosity. Gifts may come with hidden expectations. Examine the power dynamics in your exchanges. True generosity expects nothing in return.",
  },
  {
    id: 70, name: "Seven of Pentacles", numeral: "7", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["patience", "investment", "assessment"],
    upright: "Pausing to assess the harvest. Long-term investments and patient work begin to show results. Evaluate your progress honestly — is this crop worth continuing to tend, or is it time to plant new seeds?",
    reversed: "Impatience, wasted effort, or poor returns. The harvest disappoints despite your labor. Consider whether you're watering the right garden. Sometimes we must pivot.",
  },
  {
    id: 71, name: "Eight of Pentacles", numeral: "8", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["diligence", "mastery", "skill development"],
    upright: "The apprentice at the workbench. Dedicated practice, education, and skill refinement lead to mastery. Keep your head down and focus on the craft. Excellence comes from repetition with intention.",
    reversed: "Perfectionism, lack of motivation, or shortcuts. The work feels tedious or you're cutting corners. Reconnect with why you started. Mastery demands patience.",
  },
  {
    id: 72, name: "Nine of Pentacles", numeral: "9", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["luxury", "self-sufficiency", "refinement"],
    upright: "Elegant abundance earned through your own effort. The Nine of Pentacles celebrates financial independence, self-sufficiency, and the finer things in life. You've built this garden — enjoy walking through it.",
    reversed: "Over-dependence on others, shallow materialism, or setbacks in self-sufficiency. The luxury may be a facade, or independence has tipped into isolation. True wealth includes human warmth.",
  },
  {
    id: 73, name: "Ten of Pentacles", numeral: "10", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["legacy", "inheritance", "lasting wealth"],
    upright: "The culmination of material success. Generational wealth, family legacy, and lasting security define this card. What you build now echoes through time. Consider not just your fortune, but your heritage.",
    reversed: "Family financial disputes, loss of inheritance, or instability in what seemed permanent. Legacy crumbles without maintenance. Address family matters before they become feuds.",
  },
  {
    id: 74, name: "Page of Pentacles", numeral: "P", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["ambition", "desire to learn", "new financial opportunity"],
    upright: "A studious seeker of earthly wisdom. The Page of Pentacles brings news of financial opportunities, educational pursuits, or practical new ventures. Approach with diligence and a beginner's mind.",
    reversed: "Lack of progress, procrastination, or unrealistic financial plans. Dreams without action remain fantasies. Create a practical plan and take the first tangible step.",
  },
  {
    id: 75, name: "Knight of Pentacles", numeral: "Kn", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["reliability", "hard work", "routine"],
    upright: "Steady, dependable, and hardworking. The Knight of Pentacles moves slowly but never stops. Reliability and methodical effort bring results that flashier approaches cannot. Trust the process.",
    reversed: "Stagnation, laziness, or obsessive perfectionism. The steady approach becomes stuck in a rut. Sometimes you need to shake up the routine to make progress.",
  },
  {
    id: 76, name: "Queen of Pentacles", numeral: "Q", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["nurturing", "practical abundance", "down-to-earth"],
    upright: "The abundant nurturer. The Queen of Pentacles creates a warm, prosperous home through practical wisdom and generous care. She balances material comfort with genuine warmth. Care for your body, home, and finances with love.",
    reversed: "Neglect of home life, work-life imbalance, or financial dependency. Practical matters have been ignored or you've lost touch with simple pleasures. Return to earth and tend your garden.",
  },
  {
    id: 77, name: "King of Pentacles", numeral: "K", arcana: "minor", suit: "pentacles",
    symbol: "🌿", element: "Earth",
    keywords: ["wealth", "business mastery", "stability"],
    upright: "The master of the material world. The King of Pentacles has built an empire of wealth and security through discipline and savvy. Financial wisdom, business success, and generous stability define his reign. Build to last.",
    reversed: "Greed, stubbornness, or materialism without soul. Wealth becomes an end rather than a means. A kingdom built only on gold eventually collapses. Remember what truly matters.",
  }
];

// ═══════════════════════════════════════
//  SUIT METADATA
// ═══════════════════════════════════════
const SUIT_META = {
  wands:     { name: "Wands",     element: "Fire",  color: "#e84c3d", icon: "🔥", theme: "Passion, creativity, willpower, ambition" },
  cups:      { name: "Cups",      element: "Water", color: "#3498db", icon: "💧", theme: "Emotions, love, intuition, relationships" },
  swords:    { name: "Swords",    element: "Air",   color: "#95a5a6", icon: "💨", theme: "Intellect, truth, conflict, communication" },
  pentacles: { name: "Pentacles", element: "Earth", color: "#27ae60", icon: "🌿", theme: "Material, wealth, health, practical matters" },
};

// Roman numeral helper for display
const ROMAN = {
  "0": "0", "A": "A", "2": "II", "3": "III", "4": "IV", "5": "V",
  "6": "VI", "7": "VII", "8": "VIII", "9": "IX", "10": "X",
  "P": "Page", "Kn": "Knight", "Q": "Queen", "K": "King",
  "I": "I", "II": "II", "III": "III", "IV": "IV", "V": "V",
  "VI": "VI", "VII": "VII", "VIII": "VIII", "IX": "IX", "X": "X",
  "XI": "XI", "XII": "XII", "XIII": "XIII", "XIV": "XIV", "XV": "XV",
  "XVI": "XVI", "XVII": "XVII", "XVIII": "XVIII", "XIX": "XIX",
  "XX": "XX", "XXI": "XXI",
};
